apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hotel-reservation-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
    targetRevision: production
    path: apps/hotel-reservation
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
