apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
      targetRevision: master
      ref: values
    
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: "0.31.0"
      helm:
        valueFiles:
          - $values/platform/vault/values.vault.base.yaml

    - repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
      targetRevision: master
      path: platform/vault
      directory:
        include: 'ingress.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
