apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    # Kyverno Helm Chart
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: 3.1.4
      helm:
        valueFiles:
          - $values/platform/policy/kyverno-values.yaml

    # Values from Git
    - repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
