
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  # Use "sources" to reference both the Git repo (values) and the Helm chart repo (chart)
  sources:
    - repoURL: 'https://charts.external-secrets.io'
      chart: external-secrets
      targetRevision: "1.1.0"
      helm:
        valueFiles:
          - $values/platform/external-secrets/values.external-secrets.yaml
    - repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
      targetRevision: main
      ref: values
      path: platform/external-secrets

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
