apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-opensearch-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # Deploy before dashboards
spec:
  project: default

  source:
    repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
    targetRevision: main
    path: platform/logging
    directory:
      recurse: false
      include: 'opensearch-cluster.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
