apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phoenix-staging-set
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
    targetRevision: staging
    path: apps/hotel-reservation
  destination:
    server: https://kubernetes.default.svc
    namespace: staging # Deploy to the staging namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true