apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phoenix-staging-set
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
    targetRevision: master
    path: apps/hotel-reservation
    helm:
      valueFiles:
        - environments/staging/staging-frontend.yaml
        - environments/staging/staging-identity-service.yaml
        - environments/staging/staging-hotel-service.yaml
        - environments/staging/staging-booking-service.yaml
        - environments/staging/staging-search-service.yaml
        - environments/staging/staging-notification-service.yaml
        - environments/staging/staging-rabbitmq.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: phoenix-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
