apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phoenix-production-set
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
    targetRevision: master
    path: apps/hotel-reservation
    helm:
      valueFiles:
        - environments/production/frontend.yaml
        - environments/production/identity-service.yaml
        - environments/production/hotel-service.yaml
        - environments/production/booking-service.yaml
        - environments/production/search-service.yaml
        - environments/production/notification-service.yaml
        - environments/production/rabbitmq.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: phoenix-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
