apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: phoenix-staging-set
  namespace: argocd
spec:
  # 1. Generator: Find all service directories under 'apps/'
  generators:
  - git:
      repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
      revision: main
      directories:
      - path: apps/* # Discovers all folders (e.g., user-service, payment-service)

  # 2. Template: The Application definition to be generated for each service
  template:
    metadata:
      # Generated App Name: phoenix-staging-user-service
      name: 'phoenix-staging-{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "10" # Run after all platform infra (Wave 7)
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: phoenix-staging # Target the dedicated staging namespace

      sources:
        # Source 1: The Git Repo (Value Provider) - Required for $values references
        - repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
          targetRevision: main
          ref: values
        
        # Source 2: The Base Helm Chart (The Application Code)
        # The 'path' points to the specific service folder found by the generator.
        - repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
          targetRevision: main
          path: '{{path}}' # e.g., apps/user-service
          helm:
            # CRITICAL: Define the loading order for environment overrides
            valueFiles:
              # 1. Load the Base Defaults (Lowest Priority)
              - '{{path}}/values.yaml'
              # 2. Load the Staging Overlays (Highest Priority - Overwrites base)
              - 'environments/staging/{{path.basename}}-config.yaml'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
