apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phoenix-production-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
    targetRevision: master
    path: environments/production/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: phoenix-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
