apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opensearch-admin-secret
  namespace: opensearch # CRITICAL: Must be in the same namespace as the OpenSearch pods
spec:
  # Check Vault for changes every 15 minutes
  refreshInterval: "100m" 
  
  secretStoreRef:
    # References the ClusterSecretStore created above
    name: vault-cluster-store 
    kind: ClusterSecretStore
  
  target:
    # Name of the final Kubernetes Secret object
    name: opensearch-admin-secret 
    creationPolicy: Owner
    
  data:
    # Map the value from Vault to the key 'value' in the Kubernetes Secret
    - secretKey: username
      remoteRef:
        # Path where the password must be stored in Vault (KV v2 structure)
        key: kv/data/secret/opensearch/admin-password 
        # The key inside the Vault secret path.
        property: username

    - secretKey: password
      remoteRef:
        key: kv/data/secret/opensearch/admin-password
        property: password

    - secretKey: cookie
      remoteRef:
        key: kv/data/secret/opensearch/admin-password
        property: cookie
