apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-code-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: transfer-pod
  namespace: default
spec:
  containers:
  - name: transfer
    image: ubuntu
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y tar && sleep infinity"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /workspace
      name: source-volume
  volumes:
  - name: source-volume
    persistentVolumeClaim:
      claimName: source-code-pvc
