apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
    targetRevision: production
    path: platform/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 79.7.1
      helm:
        valueFiles:
          - $values/platform/monitoring/values.yaml
    - repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
      targetRevision: production
      ref: values
    - repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
      targetRevision: production
      path: platform/monitoring
      directory:
        include: 'grafana-allow-policy.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
    targetRevision: production
    path: platform/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hotel-reservation-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
    targetRevision: production
    path: apps/hotel-reservation
  destination:
    server: https://kubernetes.default.svc
    namespace: production
