apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: phoenix-prod-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - "*"
    port:
      name: http-prod
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - "*"
    port:
      name: https-prod
      number: 443
      protocol: HTTPS
    tls:
      credentialName: pheonix-live-tls
      mode: SIMPLE
