apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  
  sources:
    # 1. The Official Prometheus Community Chart
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 79.7.1
      helm:
        valueFiles:
          - $values/platform/monitoring/values.yaml

    # 2. Your Repo (For Values)
    - repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
      targetRevision: staging
      ref: values

    # 3. Your Repo (For Manifests)
    - repoURL: https://github.com/theenuka/pheonix-booking-config-repo.git
      targetRevision: staging
      path: platform/monitoring
      directory:
        include: 'grafana-allow-policy.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
