apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pheonix-live-cert
  namespace: istio-ingress  # Must be where the Gateway lives
spec:
  secretName: pheonix-live-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.pheonix.live"
  dnsNames:
    - "pheonix.live"
    - "*.pheonix.live"
