apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingress
  servers:
  # Port 80: HTTP Traffic
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "k8s-istioing-phoenixa-873394dda6-1066746258.us-east-1.elb.amazonaws.com"
    - "k8s-argocd-argocdse-f4b1608958-1653558420.us-east-1.elb.amazonaws.com"
