apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-vs
  namespace: harbor
spec:
  hosts:
  - "k8s-istioing-phoenixa-873394dda6-1066746258.us-east-1.elb.amazonaws.com"
  gateways:
  - istio-ingress/main-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: harbor-core
        port:
          number: 80
