apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: phoenix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: ttl.sh/phoenix-hotel-search-service-v1:2h
        ports:
        - containerPort: 7105
        env:
        - name: MONGODB_CONNECTION_STRING
          value: "mongodb://mongodb:27017/hotel-booking"
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: phoenix-app
spec:
  selector:
    app: search-service
  ports:
  - port: 80
    targetPort: 7105