apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: phoenix-app
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: hotel-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/part-of: hotel-reservation
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "7008"
        prometheus.io/path: "/metrics"
        fluentbit.io/parser: json
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
        - name: api-gateway
          image: k8s-harbor-harborin-04b31170bb-1679859835.us-east-1.elb.amazonaws.com/phoenix-project/phoenix-api-gateway-service:dea7c76e5af227a5e121946fa9bee23711b3db8e
          ports:
            - containerPort: 7008
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "768Mi"
              cpu: "700m"
          livenessProbe:
            tcpSocket:
              port: 7008
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 7008
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: asgardeo-config
          env:
            - name: IDENTITY_SERVICE_URL
              value: "http://identity-service"
            - name: HOTEL_SERVICE_URL
              value: "http://hotel-service"
            - name: BOOKING_SERVICE_URL
              value: "http://booking-service"
            - name: SEARCH_SERVICE_URL
              value: "http://search-service"
            - name: JWT_SECRET_KEY
              value: "my-super-secret-key-change-this-later"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.observability:4317
            - name: OTEL_SERVICE_NAME
              value: api-gateway
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.namespace=phoenix-app,service.name=api-gateway,deployment.environment=prod
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: phoenix-app
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 7008
      targetPort: 7008
  template:
    spec:
      containers: []
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
  namespace: phoenix-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
  template:
    spec:
      containers: []
