apiVersion: v1
kind: Namespace
metadata:
  name: phoenix-app
  labels:
    istio-injection: enabled
    goldilocks.fairwinds.com/enabled: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    configmanagement.gke.io/cluster-selector: phoenix-app